# 构建脚本的配置文件

[build]
# 默认编译器。可选项: "default", "gcc", "clang"
compiler = "gcc"

# 编译器警告级别开关
# 1: 启用基础警告 (-Wall)。
# 2: 启用扩展警告 (-Wall -Wextra -Wpedantic)。(推荐)
# 3: 启用严格的开发者模式 (级别2 + 将所有警告视为错误)。
warning_level = 3


# ==================== [新增] ====================
# 是否启用链接时优化 (LTO)。
# LTO可以提升发布版本的运行性能并减小文件大小，但会增加链接时间。
# true = 启用, false = 禁用
enable_lto = false